name: Pirates
version: '${project.version}'
main: net.novorex.pirates.Main
api-version: 1.16
authors: [ Diaboy01, NovorexNetwork ]
description: novorex.net
website: novorex.net

commands:
  inv:
  modifydamage:
  claim:
  talk:
  dukaten:
  time:
  shop: